### PR TITLE
Metronome Improvements

### PR DESCRIPTION
**Pull request by abelRoland**
Metronome Improvements:

- [x] Create a `measure` state to hold data if measure is simple 's' or compost 'c';
- [x] Fixing `handleBpmSliderChange` and `handleBpmInputChange` in order to accept on-the-fly tempo changes;
- [x] Adding `currentTime = 0` to handle fast velocity tempo;
- [x] Create `click3.wav`;
- [x] Adding `click3.wav` on the logic of compost measure;
- [x] Update state  of `measure` with radio button `onClick`;
- [x] Change `startStop()` and `playClick()` with conditional statement to handle different kinds of measure;
- [x] Fixing on-the-fly beats per measure change between simple measure (2/4) and compost measure (6/8);
- [x] Set `clearInterval(timer)` when unmount. (That was not me was @GordonPmnt , I just copy and paster it here :)

### CODE REVIEW

**Comment by BasileRaiwet** [comment]
@abelRoland , there's conflcits on `Metronom.jsx`. Can you check and test ? 
(you can directly resolve conflicts on github (it will create a new commit) and then pull on your local branch in order to check if it's the same behavior.

**Comment by abelRoland** [comment]
> @abelRoland , there's conflcits on `Metronom.jsx`. Can you check and test ?
> (you can directly resolve conflicts on github (it will create a new commit) and then pull on your local branch in order to check if it's the same behavior.

Done

**Comment by BasileRaiwet** [comment]
@GordonPmnt Is it ok for you if I review this one ? (I will do that later this evening).

**Comment by GordonPmnt** [comment]
@BasileRaiwet Sure 👍 :)

**Pull request merged**
